### ISSUE TITLE
Hashtag not allowed in DB Password

### ISSUE THREAD

**Issue by zivbk1** [silentworks/waiting-list#4]
I wanted to pass this along since it stumped me for a while.
I was getting errors with my connection when I was trying to run `m:up` because there was a `#` in the password.  When I pulled that out and tried again, it worked.

Also, I wasn't sure which connection string to use, so I went with the 'URI' option since it would include the password.

This information might be good to add to your ReadMe.

**Comment by silentworks** [comment]
Thanks for the feedback, I will add this information to the ReadMe.

**Comment by silentworks** [comment]
README updated at this commit https://github.com/silentworks/waiting-list/commit/9b36e81dd87e3221ac3ac35b801c6471e7f129bd
